disabled_rules: # rule identifiers to exclude from running
  # - colon
  #- comma
  #- control_statement
  # - trailing_whitespace
  # - legacy_cggeometry_functions
opt_in_rules: # some rules are only opt-in
  - empty_count
  #- missing_docs
included: # paths to include during linting. `--path` is ignored if present.
  - Movies
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
# configurable rules can be customized from this configuration file
# binary rules can set their severity level
force_cast: warning # implicitly
force_try:
  severity: warning # explicitly
# rules that have both warning and error levels, can set just the warning level
# implicitly
line_length: 300
# they can set both implicitly with an array
type_body_length:
  - 350 # warning
  - 450 # error
# or they can set both explicitly
file_length:
  warning: 600
  error: 1200
# naming rules can set warnings/errors for min_length and max_length
# additionally they can set excluded names
type_name:
  min_length: 4 # only warning
  max_length: # warning and error
    warning: 40
    error: 50
  excluded: iPhone # excluded via string
identifier_name:
  min_length:
    warning: 0
    error: 0
large_tuple:
    warning: 4
    error: 8
function_body_length:
    warning: 60
    error: 100
reporter: "xcode"
